reddit_on_rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#new'

  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new]
  resources :subs, only: [:create, :new, :index, :show, :update, :edit] 
  resources :posts, only: [:create, :new, :show, :destroy, :index]
end

reddit_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_on_rails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub
  
  has_many :subs, 
    through: :post_subs,
    source: :sub
end

reddit_on_rails/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id      :integer          not null, primary key
#  post_id :integer          not null
#  sub_id  :integer          not null
#

class PostSub < ApplicationRecord
  validates :post_id, uniqueness: { scope: :sub_id }
  belongs_to :post
  belongs_to :sub
end

reddit_on_rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub
   
  has_many :posts, dependent: :destroy,
    through: :post_subs,
    source: :post
end

reddit_on_rails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :posts,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Post

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Post

  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  # has

  #fig vape

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
end

reddit_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  helper_method :list_all_subs

  def list_all_subs
    Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, :subs_id)
  end
end

reddit_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

reddit_on_rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_mod, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.user_id = current_user.id
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def ensure_mod
    
    redirect_to subs_url unless current_user.id == Sub.find(params[:id]).user.id
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to new_user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_on_rails/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

reddit_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Sign out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign in</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% end %>
    <%= render 'layouts/errors' %>
    <%= yield %>
  </body>
</html>

reddit_on_rails/app/views/posts/new.html.erb
<h1> New Post </h2>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <% list_all_subs.each do |sub| %>
      <input type="checkbox" 
        name="post[sub_ids][]" 
        value="<%= sub.id %>" 
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <% end %>
  </select>
  <input type="text" name="sub[title]">
  <br>
  <textarea name="sub[content]" rows="6" cols="40"></textarea>
  <br>
  <input type="submit" value="Submit post">
</form>

reddit_on_rails/app/views/subs/edit.html.erb
<center>
  <h2>Edit Sub</h2>
  <form action="<%= sub_url(@sub)%>" method="post">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
      <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <br><br>
    <label>Description:
      <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <br><br>
    <input type="submit" value="Update Sub">
  </form>
</center>

reddit_on_rails/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
  <li>

      <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
      <a href="<%= edit_sub_url(sub) %>">Edit</a>
  </li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">New Sub</a>

reddit_on_rails/app/views/subs/new.html.erb
<h1>Create Sub</h1>

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title:
    <input type="text" name="sub[title]" value="">
  </label>
  <label>Description:
    <input type="textarea" name="sub[description]" value="">
  </label>

  <input type="submit" value="Create sub">
</form>

reddit_on_rails/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<h3><%= @sub.description %></h3>

reddit_on_rails/app/views/users/new.html.erb
<h1>Sign up!</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username:
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>